### ISSUE TITLE
EmailConfigUtil

### ISSUE THREAD

**Issue by juandro** [athulmurali/plagiarismDetector#1]
Exception in thread "main" java.lang.NullPointerException
	at com.blacksheep.util.EmailConfigUtil.returnProperties(EmailConfigUtil.java:46)
	at com.blacksheep.util.EMailer.<init>(EMailer.java:44)
	at com.blacksheep.BlackSheepApplication.main(BlackSheepApplication.java:27)

**Comment by athulmurali** [comment]
Please make sure you have all the properties configured in main/resources/**

For this error, I have added a file in the latest commit. 

Similarly, for aws, logger config, you will have to add those files. Please go through the config file added. 

Closing this issue for now. 

_Please hit the star button if this repo helped or you loved it!_
